---
- name: "Create {{ letsencrypt_container_name }}_acme volume"
  docker_volume:
    name: "{{ letsencrypt_container_name }}_acme"
    state: present

- name: Push env file
  template:
    src: "{{ role_path }}/templates/letsencrypt.env.j2"
    dest: "{{ letsencrypt_remote_env_path }}"
  register: le_envpush

- name: Spawn letsencrypt container
  docker_container:
    name: "{{ letsencrypt_container_name }}"
    image: "ghcr.io/nginx-proxy/acme-companion:{{ letsencrypt_image_tag|string }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ letsencrypt_container_name }}_acme:/etc/acme.sh"
    volumes_from: "{{ nginx_container_name }}"
    env_file: "{{ letsencrypt_remote_env_path }}"
    restart_policy: "{{ letsencrypt_restart_policy }}"
    recreate: "{{ 'yes' if le_envpush.changed else 'no' }}"
    state: "{{ letsencrypt_container_state }}"
