---
- include_tasks: "{{ role_path }}/tasks/network.yml"
  tags: install-nginx

- include_tasks: "{{ role_path }}/tasks/volumes.yml"
  tags: install-nginx

- include_tasks: "{{ role_path }}/tasks/nginx.yml"
  tags: install-nginx

- include_tasks: "{{ role_path }}/tasks/letsencrypt.yml"
  when: letsencrypt|bool
  tags: install-nginx, install-letsencrypt

