- import_tasks: "{{ role_path }}/tasks/network.yml"

- import_tasks: "{{ role_path }}/tasks/volumes.yml"

- import_tasks: "{{ role_path }}/tasks/nginx.yml"

- import_tasks: "{{ role_path }}/tasks/letsencrypt.yml"
