- name: "Ensure {{ nginx_container_name }}_certs volume exists"
  docker_volume:
    name: "{{ nginx_container_name }}_certs"
    state: present

- name: "Ensure {{ nginx_container_name }}_conf.d volume exists"
  docker_volume:
    name: "{{ nginx_container_name }}_conf.d"
    state: present

- name: "Ensure {{ nginx_container_name }}_vhost.d volume exists"
  docker_volume:
    name: "{{ nginx_container_name }}_vhost.d"
    state: present

- name: "Ensure {{ nginx_container_name }}_htpasswd volume exists"
  docker_volume:
    name: "{{ nginx_container_name }}_htpasswd"
    state: present

- name: "Ensure {{ nginx_container_name }}_html volume exists"
  docker_volume:
    name: "{{ nginx_container_name }}_html"
    state: present

