- name: Ensure nginx_cert volume exists
  docker_volume:
    name: nginx_cert
    state: present

- name: Ensure nginx_conf.d volume exists
  docker_volume:
    name: nginx_conf.d
    state: present

- name: Ensure nginx_cert volume exists
  docker_volume:
    name: nginx_cert
    state: present

- name: Ensure nginx_vhost.d volume exists
  docker_volume:
    name: nginx_vhost.d
    state: present

- name: Ensure nginx_htpasswd volume exists
  docker_volume:
    name: nginx_htpasswd
    state: present

- name: Ensure nginx_html volume exists
  docker_volume:
    name: nginx_html
    state: present
