- name: Start nginx container
  docker_container:
    name: nginx
    state: started

- name: Stop nginx container
  docker_container:
    name: nginx
    state: stopped

- name: Restart nginx container
  docker_container:
    name: nginx
    state: started
    restart: yes